title: Cody Yeh (葉)
description: "Materials & Biomedical Engineer | Specializing in Quality Assurance & Forensic Engineering"
theme: jekyll-theme-cayman # 換成 Cayman 主題，視覺上會更有設計感

# 你的專屬導覽選單 (跟朋友的順序做出區隔)
header_pages:
  - index.md
  - technical_projects.md  # 強調技術專案
  - research.md            # 獨立出研究與論文
  - contact.md
